version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5217:80"
    depends_on:
      - db
    networks:
      - app-network
  
  db:
    image: postgres:12
    container_name: db
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    restart: on-failure
    networks:
      - app-network

volumes:
  pgdata: {}

networks:
  app-network:
    driver: bridge